######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 3 15:21:33 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += defs.h SnakeNetworkClient.h SnakeNetworkClientDialog.h
SOURCES += main.cpp SnakeNetworkClient.cpp SnakeNetworkClientDialog.cpp
