######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 2 23:42:19 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += SnakeNetworkClientDialog.h
SOURCES += main.cpp SnakeNetworkClientDialog.cpp
