######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 1 20:12:27 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += defs.h Point.h Snake.h SnakeNetworkServer.h
SOURCES += main.cpp Point.cpp Snake.cpp SnakeNetworkServer.cpp
